version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "bazel"
    directory: "/"
    schedule:
      interval: "weekly"
