"Repository rules for importing remote apk packages"

load(":util.bzl", "util")

# Bump this constant whenever a behavioral change requires existing cached
# repository rule results to be invalidated.
RULES_APKO_CACHE_KEY = "2"

APK_IMPORT_TMPL = """\
# Generated by apk_import. DO NOT EDIT
filegroup(
    name = "all",
    srcs = {srcs},
    visibility = ["//visibility:public"]
)
"""

def _auth(rctx, url):
    if "HTTP_AUTH" not in rctx.os.environ:
        return {}
    http_auth = rctx.os.environ["HTTP_AUTH"]

    parts = http_auth.split(":", 3)
    if len(parts) != 4:
        fail("malformed HTTP_AUTH environment variable wanted basic:REALM:USER:PASSWORD, but got {} parts", len(parts))

    if parts[0].lower() != "basic":
        fail("malformed HTTP_AUTH environment variable wanted basic:REALM:USER:PASSWORD, but got {} for first part", parts[0])

    if not url.startswith("https://{}".format(parts[1])):
        return {}

    return {
        url: {
            "type": "basic",
            "login": parts[2],
            "password": parts[3],
        },
    }

def _download(rctx, url, rng, **kwargs):
    return rctx.download(
        url = [url],
        headers = {"Range": [rng]},
        auth = _auth(rctx, url),
        **kwargs
    )

def _apk_import_impl(rctx):
    repo = util.repo_url(rctx.attr.url, rctx.attr.architecture)
    repo_escaped = util.url_escape(repo)

    output = "{}/{}/{}-{}".format(repo_escaped, rctx.attr.architecture, rctx.attr.package_name, rctx.attr.version)

    control_sha256 = util.normalize_sri(rctx, rctx.attr.control_checksum)
    data_sha256 = util.normalize_sri(rctx, rctx.attr.data_checksum)

    control_output = "{}/{}.ctl.tar.gz".format(output, control_sha256)
    data_output = "{}/{}.dat.tar.gz".format(output, data_sha256)
    apk_output = "{}.apk".format(output)

    # Some apks (notably most wolfi packages) ship without an in-apk
    # signature segment; the lockfile encodes that as an empty range. Issuing
    # a Range request with an empty value would cause the origin to ignore
    # the header and return the full file as the "signature", which then
    # gets concatenated with control+data to produce a doubled apk.
    sig_output = None
    if rctx.attr.signature_range:
        sig_output = "{}/{}.sig.tar.gz".format(output, control_sha256)
        _download(
            rctx,
            url = rctx.attr.url,
            rng = rctx.attr.signature_range,
            output = sig_output,
            # TODO: signatures does not have stable checksums. find a way to fail gracefully.
            # integrity = rctx.attr.signature_checksum,
        )
    _download(
        rctx,
        url = rctx.attr.url,
        rng = rctx.attr.control_range,
        output = control_output,
        integrity = rctx.attr.control_checksum,
    )
    _download(
        rctx,
        url = rctx.attr.url,
        rng = rctx.attr.data_range,
        output = data_output,
        integrity = rctx.attr.data_checksum,
    )

    util.concatenate_gzip_segments(
        rctx,
        output = apk_output,
        signature = sig_output,
        control = control_output,
        data = data_output,
    )

    # Every file this repository holds was written above, at a path derived from
    # the attrs, so list them explicitly rather than rediscovering them with a
    # recursive glob: globbing walks every directory in the repository, and when
    # the repo is lazily materialized out of a repo contents cache each of those
    # directory reads becomes a network round trip, repeated for every apk_import
    # repo in the build.
    srcs = [control_output, data_output, apk_output]
    if sig_output:
        srcs.append(sig_output)
    rctx.file("BUILD.bazel", APK_IMPORT_TMPL.format(srcs = repr(srcs)))

    # The control and data segments - the whole apk payload - are integrity
    # pinned from the lockfile, and every path written here is derived from the
    # attrs, so the contents are a pure function of the recorded inputs.
    #
    # Two things are deliberately not treated as blockers:
    #  - The signature segment is fetched unpinned (see the TODO above). It is a
    #    fixed byte range of an immutable published apk, and apko verifies it
    #    against the keyring at build time, so a cache hit cannot smuggle in a
    #    signature that a fresh fetch would have rejected.
    #  - `HTTP_AUTH` is read via `rctx.os.environ`, which is not a recorded
    #    input. It only decides whether a request is authorised, never what the
    #    verified bytes are, so it cannot fork the contents for a given key.
    #
    # A rules_apko release can invalidate stale cache entries by bumping
    # `RULES_APKO_CACHE_KEY`, which flows into the `rules_apko_cache_key` attr.
    return util.repo_metadata(rctx, reproducible = True)

apk_import = repository_rule(
    implementation = _apk_import_impl,
    attrs = {
        "package_name": attr.string(mandatory = True),
        "version": attr.string(mandatory = True),
        "architecture": attr.string(mandatory = True),
        "url": attr.string(mandatory = True),
        "signature_range": attr.string(mandatory = True),
        "signature_checksum": attr.string(mandatory = True),
        "control_range": attr.string(mandatory = True),
        "control_checksum": attr.string(mandatory = True),
        "data_range": attr.string(mandatory = True),
        "data_checksum": attr.string(mandatory = True),
        "rules_apko_cache_key": attr.string(default = RULES_APKO_CACHE_KEY),
    },
)

APK_REPOSITORY_TMPL = """\
# Generated by apk_repository. DO NOT EDIT
filegroup(
    name = "index",
    srcs = [{index}],
    visibility = ["//visibility:public"]
)
"""

def _apk_repository_impl(rctx):
    repo = util.repo_url(rctx.attr.url, rctx.attr.architecture)
    repo_escaped = util.url_escape(repo)
    index_output = "{}/{}/APKINDEX/latest.tar.gz".format(repo_escaped, rctx.attr.architecture)
    rctx.download(
        url = [rctx.attr.url],
        auth = _auth(rctx, rctx.attr.url),
        output = index_output,
    )

    # As in `apk_import`, name the one file written above instead of globbing the
    # tree to rediscover it.
    rctx.file("BUILD.bazel", APK_REPOSITORY_TMPL.format(index = repr(index_output)))

    # Deliberately not marked reproducible.
    #
    # `url` points at the repository's live `APKINDEX.tar.gz`, which is rewritten
    # every time a package is published, and the download is not checksum pinned.
    # The contents are therefore a function of fetch time, not of the attrs, and
    # sharing them across machines could pair a lockfile with an index that
    # predates it.
    return util.repo_metadata(rctx, reproducible = False)

apk_repository = repository_rule(
    implementation = _apk_repository_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "architecture": attr.string(mandatory = True),
    },
)

APK_KEYRING_TMPL = """\
# Generated by apk_import. DO NOT EDIT
filegroup(
    name = "keyring",
    srcs = ["{public_key}"],
    visibility = ["//visibility:public"]
)
"""

def _cachePathFromURL(url):
    """
    Translates URL to a name of local directory that can be used to represent prefetched content of the URL.

    Mimicks https://github.com/chainguard-dev/go-apk/blob/7b08e8f3b0fcaa0f0a44757aedf23f6778cd8e4f/pkg/apk/cache.go#L326C6-L326C22
    Is interprets URL as following path: {repo}/{arch}/{file} [but also used for keyring files that don't obey {arch} part].

    For RSA public key files (*.rsa.pub), the file is stored in a directory named after the full filename.

    Examples:
      https://packages.wolfi.dev/os/wolfi-signing.rsa.pub              -> https%3A%2F%2Fpackages.wolfi.dev%2F/os/wolfi-signing.rsa.pub/wolfi-signing.rsa.pub
      https://packages.wolfi.dev/os/aarch64/sqlite-libs-3.44.0-r0.apk  -> https%3A%2F%2Fpackages.wolfi.dev%2Fos/arch64/sqlite-libs-3.44.0-r0.apk
    """
    url_split = url.rsplit("/", 2)
    repo = url_split[0]
    if len(repo.split("/")) <= 3:
        # Seems the Apko adds additional "/" if the URL is short.
        repo += "/"
    repo_escaped = util.url_escape(repo)
    filename = url_split[2]

    # For RSA public key files, store them in a directory named after the full filename
    if filename.endswith(".rsa.pub"):
        return "{}/{}/{}/{}".format(repo_escaped, url_split[1], filename, filename)

    return "{}/{}/{}".format(repo_escaped, url_split[1], filename)

def _apk_keyring_impl(rctx):
    public_key = _cachePathFromURL(rctx.attr.url)
    if rctx.attr.content:
        rctx.file(public_key, rctx.attr.content)
    else:
        rctx.download(url = [rctx.attr.url], output = public_key, auth = _auth(rctx, rctx.attr.url))
    rctx.file("BUILD.bazel", APK_KEYRING_TMPL.format(public_key = public_key))

    # With `content` set nothing is fetched at all, so the repo is templated
    # purely from the attrs. Without it the key is fetched unpinned, but a
    # signing key URL names one specific key: rotation publishes a new
    # `*.rsa.pub` filename rather than rewriting an existing one, so the bytes at
    # a given `url` do not change. `_cachePathFromURL` derives the layout from
    # `url` alone, never from the host. Should that assumption ever be violated,
    # a rules_apko release can invalidate cached keyrings by bumping
    # `RULES_APKO_CACHE_KEY`.
    return util.repo_metadata(rctx, reproducible = True)

apk_keyring = repository_rule(
    implementation = _apk_keyring_impl,
    attrs = {
        "url": attr.string(mandatory = True),
        "content": attr.string(
            doc = "Raw keyring bytes (typically a PEM-encoded public key). When set, the URL is not fetched.",
        ),
        "rules_apko_cache_key": attr.string(default = RULES_APKO_CACHE_KEY),
    },
)

def _apk_filegroup_impl(ctx):
    lockfile = depset([ctx.file.lockfile])
    apks = depset(ctx.files.apks)
    indexes = depset(ctx.files.indexes)
    keyrings = depset(ctx.files.keyrings)
    return [
        DefaultInfo(files = depset(transitive = [lockfile, apks, indexes, keyrings])),
        OutputGroupInfo(
            lockfile = lockfile,
            apks = apks,
            indexes = indexes,
            keyrings = keyrings,
        ),
    ]

apk_filegroup = rule(
    implementation = _apk_filegroup_impl,
    attrs = {
        "lockfile": attr.label(doc = "Label to the `apko.lock.json` file.", allow_single_file = True, mandatory = True),
        "keyrings": attr.label_list(doc = "Labels of the keyring (public key) files.", allow_files = True, mandatory = True),
        "apks": attr.label_list(doc = "Labels of the package (apk) files.", allow_files = True, mandatory = True),
        "indexes": attr.label_list(doc = "Labels of the APKINDEX files.", allow_files = True, mandatory = True),
    },
)
