"""Provider that serves as an API for adding any files needed for apko build"""

load("@bazel_skylib//lib:paths.bzl", "paths")

_PATH_CONVENTION_DOC = """
 When referencing other files in the config yaml file use paths relative to your Bazel workspace root. 
    For example, if you want to reference source file foo/bar/baz use foo/bar/baz. If you want to reference output file of foo/bar:rule and rule's 
    output file is rule.out, reference it as foo/bar/rule.out.
"""

ApkoConfigInfo = provider(
    doc = """Information about apko config. May be used when generating apko config file instead of using hardcoded ones.
    {}
    """.format(_PATH_CONVENTION_DOC),
    fields = {
        "files": "depset of files that will be needed for building. All of them will be added to the execution of apko commands when built with Bazel.",
    },
)

def _apko_config_impl(ctx):
    config = ctx.file.config
    out = ctx.actions.declare_file(ctx.attr.name)
    ctx.actions.symlink(
        target_file = config,
        output = out,
    )

    apko_depsets = []
    for dep in ctx.attr.deps:
        if ApkoConfigInfo in dep:
            apko_depsets.append(dep[ApkoConfigInfo].files)
    direct_deps = [out]
    for dep in ctx.files.deps:
        direct_deps.append(dep)

    return [
        DefaultInfo(
            files = depset([out]),
        ),
        ApkoConfigInfo(
            files = depset(direct_deps, transitive = apko_depsets),
        ),
    ]

apko_config = rule(
    implementation = _apko_config_impl,
    attrs = {
        "deps": attr.label_list(
            allow_empty = True,
            default = [],
            allow_files = True,
            doc = """
            List of all dependencies of the config. Transitive dependencies are included based on 
            ApkoConfigInfo provider.
            """,
        ),
        "config": attr.label(
            allow_single_file = True,
            doc = """
        Config of the image. Either in source directory or generated by Bazel.
        {}
        """.format(_PATH_CONVENTION_DOC),
        ),
    },
)

def copy_to_workdir(ctx, src, dst):
    """Copy a file, directory, or list of files to a declared output.

    Uses cp instead of ctx.actions.symlink because Bazel 9 sandbox changes
    cause symlink outputs to dangle when used as inputs to subsequent
    sandboxed actions.

    When src is a list, dst must be a declared directory (tree artifact);
    each source is staged at its workspace-relative path inside dst. This
    is useful when individual destination paths cannot be declared as
    per-file outputs (see callers).

    See:
      https://github.com/bazelbuild/bazel/issues/28953
      https://github.com/bazelbuild/bazel/issues/27068

    Args:
        ctx: rule context
        src: source File or list of Files
        dst: declared output File or directory
    """

    # When f is a directory, append "/." so its contents land directly in
    # target instead of nesting at target/<basename> (Bazel pre-creates
    # declared output directories, so plain cp -r src tgt would nest).
    copy_file_cmd = lambda f, target: 'mkdir -p "{dir}" && cp -rfL "{src}" "{tgt}"'.format(
        dir = paths.dirname(target),
        src = (f.path + "/.") if f.is_directory else f.path,
        tgt = target,
    )

    # f.short_path for an external file is "../<repo>/<rel>"; strip the
    # first two segments to recover <rel> for placement in the tree artifact.
    resolve_target_path = lambda f: paths.join(dst.path, f.short_path.split("/", 2)[-1])

    cmds = ["set -e"]
    if type(src) == "list":
        inputs = src
        cmds += [copy_file_cmd(f, resolve_target_path(f)) for f in src]
    else:
        inputs = [src]
        cmds.append(copy_file_cmd(src, dst.path))

    ctx.actions.run_shell(
        inputs = inputs,
        outputs = [dst],
        command = "\n".join(cmds),
        mnemonic = "CopyToWorkdir",
        progress_message = "Staging %s" % dst.short_path,
    )

def prepare_apko_config_in_workdir(workdir, ctx):
    """Helper function to prepare inputs of apko config files for build rules.

    Args:
        workdir: workdir which the build rule will use for running apko
        ctx: build rule ctx

    Returns:
        Array of files to put as inputs to the build action.
    """
    inputs = []
    if ApkoConfigInfo in ctx.attr.config:
        for f in ctx.attr.config[ApkoConfigInfo].files.to_list():
            if f.is_directory:
                input_entry = ctx.actions.declare_directory(paths.join(workdir, f.short_path))
            else:
                input_entry = ctx.actions.declare_file(paths.join(workdir, f.short_path))
            copy_to_workdir(ctx, f, input_entry)
            inputs.append(input_entry)
    else:
        config_copy = ctx.actions.declare_file(paths.join(workdir, ctx.file.config.short_path))
        copy_to_workdir(ctx, ctx.file.config, config_copy)
        inputs.append(config_copy)
    return inputs
