"""Repository rules for translating apko.lock.json"""

load("//apko/private:util.bzl", "parse_lock", "sanitize_string")

TRANSLATE_BUILD_TMPL = """\
# Generated by apko_translate_lock. DO NOT EDIT.
filegroup(
    name = "packages", 
    srcs = {targets},
    visibility = ["//visibility:public"]
)
"""

def _translate_apko_lock_impl(rctx):
    lock = parse_lock(rctx.read(rctx.attr.lock))
    targets = []
    for package in lock["packages"]:
        name = sanitize_string("{}_{}_{}".format(package["name"], package["architecture"], package["version"]))
        targets.append("@{}//:all".format(name))
    for repository in lock["repositories"]:
        name = sanitize_string("{}_{}".format(repository["name"], repository["architecture"]))
        targets.append("@{}//:index".format(name))
    rctx.file(
        "BUILD.bazel",
        TRANSLATE_BUILD_TMPL.format(targets = targets),
    )

translate_apko_lock = repository_rule(
    implementation = _translate_apko_lock_impl,
    attrs = {
        "lock": attr.label(mandatory = True),
    },
)
