"""Repository rules for translating apko.lock.json"""

load("//apko/private:util.bzl", "parse_lock", "sanitize_string")

BUILD_TMPL = """\
# Generated by apko_translate_lock. DO NOT EDIT.
filegroup(
    name = "packages", 
    srcs = {targets},
    visibility = ["//visibility:public"]
)
"""

REPO_TMPL = """\
# Generated by apko_translate_lock. DO NOT EDIT.

load("@rules_apko//apko/private:apk.bzl", "apk_import", "apk_repository", "apk_keyring")

def apko_repositories():
{}
"""

APK_IMPORT_TMPL = """\
    apk_import(
        name = "{name}",
        package_name = "{package_name}",
        version = "{version}",
        architecture = "{architecture}",
        url ="{url}",
        signature_range = "{signature_range}",
        signature_checksum = "{signature_checksum}",
        control_range = "{control_range}",
        control_checksum = "{control_checksum}",
        data_range = "{data_range}",
        data_checksum = "{data_checksum}",
    )
"""

APK_REPOSITORY_TMPL = """\
    apk_repository(
        name = "{name}",
        url = "{url}",
        architecture = "{architecture}",
    )
"""

APK_KEYRING_TMPL = """\
    apk_keyring(
        name = "{name}",
        url = "{url}"
    )
"""

def _translate_apko_lock_impl(rctx):
    lock_file = parse_lock(rctx.read(rctx.attr.lock))
    targets = []
    defs = []

    target_name = rctx.attr.target_name if rctx.attr.target_name else rctx.name

    if "keyring" in lock_file["contents"]:
        for keyring in lock_file["contents"]["keyring"]:
            name = sanitize_string("{}_{}".format(target_name, keyring["name"]))
            targets.append("@{}//:keyring".format(name))
            defs.append(APK_KEYRING_TMPL.format(
                name = name,
                url = keyring["url"],
            ))

    for package in lock_file["contents"]["packages"]:
        name = sanitize_string("{}_{}_{}_{}".format(target_name, package["name"], package["architecture"], package["version"]))
        targets.append("@{}//:all".format(name))

        defs.append(APK_IMPORT_TMPL.format(
            name = name,
            package_name = package["name"],
            version = package["version"],
            architecture = package["architecture"],
            url = package["url"],
            signature_range = package["signature"]["range"],
            signature_checksum = package["signature"]["checksum"],
            control_range = package["control"]["range"],
            control_checksum = package["control"]["checksum"],
            data_range = package["data"]["range"],
            data_checksum = package["data"]["checksum"],
        ))

    for repository in lock_file["contents"]["repositories"]:
        name = sanitize_string("{}_{}_{}".format(target_name, repository["name"], repository["architecture"]))
        targets.append("@{}//:index".format(name))
        defs.append(APK_REPOSITORY_TMPL.format(
            name = name,
            url = repository["url"],
            architecture = repository["architecture"],
        ))

    rctx.file(
        "repositories.bzl",
        REPO_TMPL.format("\n".join(defs)),
    )

    rctx.file(
        "BUILD.bazel",
        BUILD_TMPL.format(targets = targets),
    )

translate_apko_lock = repository_rule(
    implementation = _translate_apko_lock_impl,
    attrs = {
        "lock": attr.label(mandatory = True),
        "target_name": attr.string(doc = "internal"),
    },
)
