issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/rules_apko:ref:refs/heads/main
claim_pattern:
  workflow_ref: chainguard-dev/rules_apko/.github/workflows/update-apko.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
